const mongoose=require("mongoose");
const userSchema=new mongoose.Schema(
    {
         name: {
            type:String,
            required:true,
            trim:true
        },
        email:{
            type:String,
            required:true,
            unique:true,
            lowercase:true
        },
        password:{
            type:String,
            required:true
        },
         resetPasswordToken:{
            type:String
        },
        resetPasswordExpire:{
            type:Date
        },
        role:{
            type:String,
            enum:["student","recruiter"],
            default:"student"
        },
        resume:{
            type:String,
            default:""
        },
        phone:{
            type:String
        },
        bio:{
            type:String
        },
        skills:{
            type:String
        },
        location:{
            type:String
        },
       
},
    {
        timestamps:true
    }
);
module.exports=mongoose.model("User",userSchema);